[package]
name = "highlight"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]

[[bin]]
name = "highlight"

[dependencies]
webplatform = { git = "https://github.com/mgattozzi/rust-webplatform.git" }
